# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev make

WORKDIR /app

# Copy essential files for building the package
COPY pyproject.toml ./
COPY requirements.txt ./
COPY README.md ./

# Upgrade pip and install build dependencies
RUN pip install --upgrade pip \
    && pip install hatchling \
    && pip install .

# Copy the rest of the code
COPY . .

# Default command to run the MCP server
CMD [ "python", "-m", "src.boring_news_mcp.__main__" ]
